# Generated by Django 4.2.2 on 2023-06-28 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_value', models.CharField(max_length=30, null=True)),
                ('category_for', models.CharField(choices=[('Puzzle', 'Puzzle'), ('Accessory', 'Accessory')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(max_length=25, null=True)),
                ('price', models.FloatField(null=True)),
                ('description', models.TextField(null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpeedcubeShopApp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpeedcubeShopApp.item')),
            ],
            bases=('SpeedcubeShopApp.item',),
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='SpeedcubeShopApp.item')),
                ('plastic_color', models.CharField(choices=[('Stickerless', 'Stickerless'), ('Black', 'Black'), ('Green', 'Green'), ('White', 'White')], max_length=25)),
            ],
            bases=('SpeedcubeShopApp.item',),
        ),
    ]
