# Generated by Django 4.2.2 on 2023-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedcubeShopApp', '0003_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
