# Generated by Django 4.2.2 on 2023-06-29 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedcubeShopApp', '0005_alter_shoppingcart_checked_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemorder',
            name='lube_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpeedcubeShopApp.lubeservice'),
        ),
    ]
