# Generated by Django 4.2.2 on 2023-06-29 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpeedcubeShopApp', '0006_alter_itemorder_lube_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesession',
            name='active_session',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='employee_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='SpeedcubeShopApp.employeesession'),
        ),
    ]
